name: CI

on:
  schedule:
    - cron: '0 6,12,18 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
