name: AutoSubmit

on:
  schedule:
    - cron: '* 6,12,18 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Auto Submit
        run: |
          ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
          date
          sudo apt install curl -y
          sudo apt install jq -y
          sudo bash ./submit.sh
