name: AutoSubmit

on:
  schedule:
    - cron: '0 6,12,18 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Auto Submit
        run: |
          apt install curl -y
          apt install jq -y
          bash submit.sh
