name: AutoSubmit

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Auto Submit
        run: |
          sudo apt install curl -y
          sudo apt install jq -y
          sudo bash ./submit.sh
